jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Pnative
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___develop.yml
