jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Pnative
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./src/main/docker/Dockerfile.native
        push: true
        tags: barais/grade-scope-istic:latest
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
